b = Book.find_by_token('example')
b.destroy if b
b = Book.create(name: 'Example', currency: '$')
b.update(token: 'example')
p = b.papers.create(title: 'Example')
p.items.create(name: 'salt', quantity: '1kg', orderer: 'Alice')
p.items.create(name: 'vinegar')

b = Book.find_by_token('00000000-0000-0000-0000-000000000000')
b.destroy if b
b = Book.create(name: 'Dev Book', currency: '$')
b.update(token: '00000000-0000-0000-0000-000000000000')
p = b.papers.create(title: 'First Paper', description: 'This is your first paper. Add some items you want!')
p.items.create(name: 'salt', quantity: '1kg', orderer: 'Alice', price: 10)
p.items.create(name: 'vinegar', orderer: 'Alice', price: 2)
p = b.papers.create()
p.items.create(name: 'salt', quantity: '1kg', orderer: 'Alice', price: 10)
p.items.create(name: 'vinegar', orderer: 'Alice', price: 2)
p.items.create(name: 'milk', orderer: 'Bob', price: 2.25)
p.items.create(name: 'whole leg ham', orderer: 'Bob', comment: 'only if it is discounted')
